### ISSUE TITLE
Yo como usuario debo poder cambiar mi foto de perfil y que se quede guardada en mi información de usuario

### ISSUE THREAD

**Issue by CarlaVictorio** [borjafernandez35/Proyecto_EA#25]
Dado que el usuario se encuentre en la screen profile,
le dé al botón de editar la foto de perfil,
cuando seleccione una imagen, 
y le de a guardar,
entonces la imagen se modificará en la screen,
se guardará en cloudinary,
y la url generada se guardará en el campo "avatar" del usuario.

5

**Comment by saraaguilo** [comment]
Dado que has accedido a la screen 'Profile',
cuando haces click en el botón de cambiar imagen,
entonces saldrán las fotos que están en el ordenador,
podrás elegir una para tu perfil,
y quedará guardada en los detalles de tu perfil
