### ISSUE TITLE
Yo como usuario debo poder añadir un comentario a un evento

### ISSUE THREAD

**Issue by CarlaVictorio** [borjafernandez35/Proyecto_EA#9]

**Comment by David-valero-blz** [comment]
Dado el usuario haya accedido a la screen de los detalles de un evento,
se le muestra una caja de texto, debajo un rating de 5 estrellas (la puntuación del comentario a dejar), un botón para dejar el comentario y finalmente se muestran los comentarios ya existentes.

Una vez el usuario ha rellenado la cajita de texto del comentario, ha indicado la puntuación en el rating de 5 estrellas y le ha dado al botón de "dejar comentario", el comentario se guarda en la base de datos, y se muestra en pantalla junto a los demás comentarios.

3
